# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-28 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170717_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_active',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u6fc0\u6d3b'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecond',
            name='send_type',
            field=models.CharField(choices=[('register', '\u6ce8\u518c'), ('forget', '\u5fd8\u8bb0\u5bc6\u7801'), ('update', '\u66f4\u65b0\u5bc6\u7801')], max_length=10, verbose_name='\u90ae\u7bb1\u7c7b\u578b'),
        ),
    ]
