# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-28 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'verbose_name': '\u6d4b\u8bd5\u7528\u4f8b',
                'verbose_name_plural': '\u6d4b\u8bd5\u7528\u4f8b',
            },
        ),
    ]
