# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-21 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170721_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseclass',
            options={'verbose_name': '\u8bfe\u7a0b\u5206\u7c7b', 'verbose_name_plural': '\u8bfe\u7a0b\u5206\u7c7b'},
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(default='', max_length=100, verbose_name='\u8bfe\u7a0b\u6807\u7b7e'),
        ),
    ]
