# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-21 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170721_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(upload_to='resource/%Y/%m', verbose_name='\u8d44\u6e90\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.FileField(default='', upload_to='video/%Y/%m', verbose_name='\u89c6\u9891\u6240\u5728\u8def\u5f84'),
        ),
    ]
