# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-21 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170721_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='minutes',
            field=models.IntegerField(default=0, verbose_name='\u65f6\u957f-\u5206\u949f'),
        ),
        migrations.AddField(
            model_name='video',
            name='seconds',
            field=models.IntegerField(default=0, verbose_name='\u65f6\u957f-\u79d2\u949f'),
        ),
    ]
