# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-21 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20170721_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='known_before',
            field=models.CharField(default='', max_length=150, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='learn_content',
            field=models.TextField(default='', verbose_name='\u5b66\u4e60\u5230\u7684\u77e5\u8bc6'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u6587\u4ef6\u540d'),
        ),
    ]
