# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-25 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170721_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_advan',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u5e7f\u544a'),
        ),
    ]
