# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-29 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_is_advan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(default='http://othhhjzhr.bkt.clouddn.com/courseonline-test-video-chapter.avi', max_length=100, verbose_name='\u89c6\u9891\u8def\u5f84'),
        ),
    ]
