# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-19 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgzation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='classify',
            field=models.IntegerField(choices=[(1, '\u5b66\u6821'), (2, '\u57f9\u8bad\u73ed'), (3, '\u4e2a\u4eba')], default=1, verbose_name='\u673a\u6784\u5206\u7c7b'),
        ),
    ]
