# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-20 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgzation', '0004_courseorg_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/%Y/%m', verbose_name='\u6559\u5e08\u7167\u7247'),
        ),
    ]
